parameters:
    pss.blog.manager.post.class:      PSS\Bundle\BlogBundle\Manager\PostManager
    pss.blog.manager.comment.class:   PSS\Bundle\BlogBundle\Manager\CommentManager
    pss.twig.extension.content.class: PSS\Bundle\BlogBundle\Twig\Extension\ContentExtension

services:
    pss.twig.extension.content:
        class:  %pss.twig.extension.content.class%
        public: false
        tags:
            - { name: twig.extension }


    pss.blog.manager.entity.abstract:
        abstract: true
        arguments:
            dispatcher: '@event_dispatcher'
            em: '@doctrine.orm.entity_manager'


    pss.blog.manager.post:
        parent:  pss.blog.manager.entity.abstract
        class:   %pss.blog.manager.post.class%