language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev install
  - mysql -e 'CREATE DATABASE pss_blog_test;'

script:
  - 'phpunit --coverage-text && ./vendor/bin/behat'

after_script:
  - mysql -e 'DROP DATABASE pss_blog_test;'

notifications:
  email:
    - jakub+pssblogbundleci@zalas.pl
